# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-08 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id_number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('card_number', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('card_number', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
