# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-13 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='district',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='home_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='ward',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
