# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-14 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20200113_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSet',
            fields=[
                ('codeset_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_type', models.CharField(blank=True, max_length=255)),
                ('display_value', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='cardinfo',
            old_name='id_number',
            new_name='number_id',
        ),
    ]
