# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-14 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20200114_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='gender_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='apps.CodeSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='phone_extension',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='position_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
