# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-14 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20200114_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardinfo',
            old_name='gender_id',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='home_school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_school', to='apps.CodeSet'),
            preserve_default=False,
        ),
    ]
