# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-14 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20200114_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_type', to='apps.CodeSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='crisis_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crisis_role', to='apps.CodeSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='apps.CodeSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='foreign_hire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='foreign_hire', to='apps.CodeSet'),
            preserve_default=False,
        ),
    ]
