# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-14 06:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20200114_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date(1900, 1, 1)),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='encrypt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='family_ident',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='first_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='is_active',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='is_active', to='apps.CodeSet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='supervisor',
            field=models.CharField(blank=True, default=b'', max_length=6),
        ),
    ]
