# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-15 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20200114_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardinfo',
            name='is_active',
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active', to='apps.CodeSet'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_type', to='apps.CodeSet'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='crisis_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crisis_role', to='apps.CodeSet'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='apps.CodeSet'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='foreign_hire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreign_hire', to='apps.CodeSet'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gender', to='apps.CodeSet'),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='home_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_school', to='apps.CodeSet'),
        ),
    ]
